---
docker_pkg_name: docker-engine
docker_apt_cache_valid_time: 600

docker_defaults_file_path: /etc/default/docker

ssh_port: 22

apt_key_url: hkp://p80.pool.sks-keyservers.net:80
apt_key_sig: 58118E89F3A912897C070ADBF76221572C52609D

apt_repository: deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main
docker_opts: ""
docker_group_members: []

pip_install_pip: true
pip_install_setuptools: true
pip_install_docker_py: true
pip_install_docker_compose: true
pip_version_pip: latest
pip_version_setuptools: latest
pip_version_docker_py: latest
pip_version_docker_compose: latest

kernel_update_and_reboot_permitted: no

update_docker_package: no

kernel_pkg_state: latest
cgroup_lite_pkg_state: latest
install_kernel_extras: false

