- name: en_US.UTF-8 locale create
  sudo: yes
  command:
    locale-gen en_US.UTF-8

- name: apt-get update
  sudo: yes
  apt:
    update_cache=yes
    cache_valid_time=86400

- name: Ruby Passenger installing and build
  sudo: yes
  apt:
    name='build-essential,zlib1g-dev,libssl-dev,libreadline-dev,libyaml-dev,libcurl4-openssl-dev'

- name:  PostgreSQL Installing
  sudo: yes
  apt:
    name='postgresql,python-psycopg2'

- name: Debug
  debug: msg={{ ansible_distribution_version }}

- name:  Apache settings for 14.04
  sudo: yes
  apt:
    name='apache2-mpm-worker,apache2-dev,libapr1-dev,libaprutil1-dev'
  when: "ansible_distribution_version|version_compare(14.04, '=')"

- name:  Apache settings for 16.04
  sudo: yes
  apt:
    name='apache2-dev,apache2-bin,libapr1-dev,libaprutil1-dev'
  when: "ansible_distribution_version|version_compare(16.04, '=')"


- name:  Installing tools
  sudo: yes
  apt:
    name='subversion,git'

- name: dir settings
  file: path={{ work_dir }} state=directory mode=0755
