- name: PostgreSQL user creating
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name=redmine
    password={{ db_passwd_redmine }}

- name: PostgreSQL 
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name=redmine
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    template='template0'
